language: java

jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6

# @see https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

